[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
name = "dplinknet"
version = "0.0.0"
description = "DP-LinkNet: A convolutional network for historical document image binarization"
requires-python = ">=3.6.10"
